### ISSUE TITLE
CSS 高度塌陷解决策

### ISSUE THREAD

**Issue by lidongyangLeo** [lidongyangLeo/LearnNotes#7]
```CSS
.clearfix::before,
.ckearfix::after {
   content: "";
  display: table;
  clear: both;
}
```
